module.exports = {
   main: {
      colors: {
         backgroundColor: {
            default: "var(--color-background-default)",
            most: "var(--color-background-most)",
            dark: "var(--color-background-dark)",
            brand: "var(--color-background-brand)",
            "brand-less": "var(--color-background-brand-less)",
            accent: "var(--color-background-accent)",
            "accent-less": "var(--color-background-accent-less)",
            "accent-more": "var(--color-background-accent-more)",
            error: "var(--color-background-error)",
            more: "var(--color-background-more)",
            success: "var(--color-background-success)",
            "success-more": "var(--color-background-success-more)",
            warning: "var(--color-background-warning)",
            "warning-more": "var(--color-background-warning-more)",
         },
         borderColor: {
            default: "var(--color-border-default)",
            disabled: "var(--color-border-disabled)",
            active: "var(--color-border-active)",
            error: "var(--color-border-error)",
            less: "var(--color-border-less)",
            success: "var(--color-border-success)",
         },
         textColor: {
            default: "var(--color-text-default)",
            accent: "var(--color-text-accent)",
            inverted: "var(--color-text-inverted)",
            primary: "var(--color-text-primary)",
            error: "var(--color-text-error)",
            warning: "var(--color-text-warning)",
            less: "var(--color-text-less)",
            success: "var(--color-text-success)",
            disabled: "var(--color-text-disabled)",
         },
      },
      others: {
         screens: {
            xl: "1240px",
            lg: "1024px",
            md: "768px",
            "3xl": "1536px",
            "2xl": "1400px",
            xxs: "360px",
            xs: "375px",
            sm: "640px",
         },
         fontFamily: {
            "family-accent": '"Raleway"',
            "family-body": '"Inter"',
         },
         fontSize: {
            "size-xs": "12px",
            "size-sm": "14px",
            "size-base": "16px",
            "size-lg": "18px",
            "size-xl": "20px",
            "size-2xl": "24px",
            "size-3xl": "28px",
            "size-4xl": "32px",
            "size-5xl": "36px",
            "size-xxs": "10px",
         },
         fontWeight: {
            "weight-thin": "100px",
            "weight-extralight": "200px",
            "weight-light": "300px",
            "weight-normal": "400px",
            "weight-medium": "500px",
            "weight-semibold": "600px",
            "weight-bold": "700px",
            "weight-extrabold": "800px",
            "weight-black": "900px",
         },
         letterSpacing: {
            "letter-spacing-tighter": "-0.8px",
            "letter-spacing-tight": "-0.4px",
            "letter-spacing-normal": "0px",
            "letter-spacing-wide": "0.4px",
            "letter-spacing-wider": "0.8px",
            "letter-spacing-widest": "1.6px",
            "letter-spacing-5": "5px",
            "letter-spacing-tightest": "-1px",
         },
         lineHeight: {
            3: "12px",
            4: "16px",
            5: "20px",
            6: "24px",
            7: "28px",
            8: "32px",
            9: "36px",
            10: "40px",
            none: "0px",
         },
         borderWidth: {
            "width-0": "0px",
            "width-1": "1px",
            "width-2": "2px",
            "width-4": "4px",
            "width-8": "8px",
         },
         borderRadius: {
            none: "0px",
            sm: "2px",
            DEFAULT: "4px",
            md: "6px",
            lg: "8px",
            xl: "12px",
            "xl-2": "16px",
            "xl-3": "24px",
            "xl-4": "32px",
            full: "9999px",
         },
         spacing: {
            0: "0px",
            1: "4px",
            2: "8px",
            3: "12px",
            4: "16px",
            5: "20px",
            6: "24px",
            7: "28px",
            8: "32px",
            9: "36px",
            10: "40px",
            11: "44px",
            12: "48px",
            14: "56px",
            16: "64px",
            20: "80px",
            24: "96px",
            28: "112px",
            32: "128px",
            36: "144px",
            40: "160px",
            44: "176px",
            48: "192px",
            52: "208px",
            56: "224px",
            60: "240px",
            64: "256px",
            72: "288px",
            80: "320px",
            96: "384px",
            px: "1px",
            "0-5": "2px",
            "1-5": "6px",
            "2-5": "10px",
            "3-5": "14px",
         },
      },
   },
   components: {
      input: {
         "bg-default": "var(--color-input-bg-default)",
         "required-star": "var(--color-input-required-star)",
         "bg-active": "var(--color-input-bg-active)",
         "bg-error": "var(--color-input-bg-error)",
         "bg-hover": "var(--color-input-bg-hover)",
         "placeholder-default": "var(--color-input-placeholder-default)",
         "placeholder-hover": "var(--color-input-placeholder-hover)",
         "placeholder-active": "var(--color-input-placeholder-active)",
         "placeholder-error": "var(--color-input-placeholder-error)",
         "text-default": "var(--color-input-text-default)",
         "text-hover": "var(--color-input-text-hover)",
         "text-active": "var(--color-input-text-active)",
         "text-error": "var(--color-input-text-error)",
         "border-default": "var(--color-input-border-default)",
         "border-hover": "var(--color-input-border-hover)",
         "border-active": "var(--color-input-border-active)",
         "border-error": "var(--color-input-border-error)",
         "border-disabled": "var(--color-input-border-disabled)",
         "placeholder-disabled": "var(--color-input-placeholder-disabled)",
      },
      button: {
         "primary-icon-default": "var(--color-button-primary-icon-default)",
         "primary-icon-hovered": "var(--color-button-primary-icon-hovered)",
         "primary-icon-active": "var(--color-button-primary-icon-active)",
         "primary-icon-disabled": "var(--color-button-primary-icon-disabled)",
         "primary-text-default": "var(--color-button-primary-text-default)",
         "primary-text-hovered": "var(--color-button-primary-text-hovered)",
         "primary-text-active": "var(--color-button-primary-text-active)",
         "primary-text-disabled": "var(--color-button-primary-text-disabled)",
         "primary-bg-default": "var(--color-button-primary-bg-default)",
         "primary-bg-hovered": "var(--color-button-primary-bg-hovered)",
         "primary-bg-active": "var(--color-button-primary-bg-active)",
         "primary-bg-disabled": "var(--color-button-primary-bg-disabled)",
         "primary-border-default": "var(--color-button-primary-border-default)",
         "primary-border-hovered": "var(--color-button-primary-border-hovered)",
         "primary-border-active": "var(--color-button-primary-border-active)",
         "primary-border-disabled":
            "var(--color-button-primary-border-disabled)",
         "inverted-text-default": "var(--color-button-inverted-text-default)",
         "inverted-bg-default": "var(--color-button-inverted-bg-default)",
         "inverted-bg-hovered": "var(--color-button-inverted-bg-hovered)",
         "inverted-bg-active": "var(--color-button-inverted-bg-active)",
         "inverted-bg-disabled": "var(--color-button-inverted-bg-disabled)",
         "inverted-text-hovered": "var(--color-button-inverted-text-hovered)",
         "inverted-text-active": "var(--color-button-inverted-text-active)",
         "inverted-text-disabled": "var(--color-button-inverted-text-disabled)",
         "inverted-icon-default": "var(--color-button-inverted-icon-default)",
         "inverted-icon-hovered": "var(--color-button-inverted-icon-hovered)",
         "inverted-icon-active": "var(--color-button-inverted-icon-active)",
         "inverted-icon-disabled": "var(--color-button-inverted-icon-disabled)",
         "inverted-border-default":
            "var(--color-button-inverted-border-default)",
         "inverted-border-hovered":
            "var(--color-button-inverted-border-hovered)",
         "inverted-border-active": "var(--color-button-inverted-border-active)",
         "inverted-border-disabled":
            "var(--color-button-inverted-border-disabled)",
         "secondary-text-default": "var(--color-button-secondary-text-default)",
         "secondary-bg-default": "var(--color-button-secondary-bg-default)",
         "secondary-bg-hovered": "var(--color-button-secondary-bg-hovered)",
         "secondary-bg-active": "var(--color-button-secondary-bg-active)",
         "secondary-bg-disabled": "var(--color-button-secondary-bg-disabled)",
         "secondary-text-hovered": "var(--color-button-secondary-text-hovered)",
         "secondary-text-active": "var(--color-button-secondary-text-active)",
         "secondary-text-disabled":
            "var(--color-button-secondary-text-disabled)",
         "secondary-icon-default": "var(--color-button-secondary-icon-default)",
         "secondary-icon-hovered": "var(--color-button-secondary-icon-hovered)",
         "secondary-icon-active": "var(--color-button-secondary-icon-active)",
         "secondary-icon-disabled":
            "var(--color-button-secondary-icon-disabled)",
         "secondary-border-default":
            "var(--color-button-secondary-border-default)",
         "secondary-border-hovered":
            "var(--color-button-secondary-border-hovered)",
         "secondary-border-active":
            "var(--color-button-secondary-border-active)",
         "secondary-border-disabled":
            "var(--color-button-secondary-border-disabled)",
         "transparent-text-default":
            "var(--color-button-transparent-text-default)",
         "transparent-bg-default": "var(--color-button-transparent-bg-default)",
         "transparent-bg-hovered": "var(--color-button-transparent-bg-hovered)",
         "transparent-bg-active": "var(--color-button-transparent-bg-active)",
         "transparent-bg-disabled":
            "var(--color-button-transparent-bg-disabled)",
         "transparent-text-hovered":
            "var(--color-button-transparent-text-hovered)",
         "transparent-text-active":
            "var(--color-button-transparent-text-active)",
         "transparent-text-disabled":
            "var(--color-button-transparent-text-disabled)",
         "transparent-icon-default":
            "var(--color-button-transparent-icon-default)",
         "transparent-icon-hovered":
            "var(--color-button-transparent-icon-hovered)",
         "transparent-icon-active":
            "var(--color-button-transparent-icon-active)",
         "transparent-icon-disabled":
            "var(--color-button-transparent-icon-disabled)",
         "transparent-border-default":
            "var(--color-button-transparent-border-default)",
         "transparent-border-hovered":
            "var(--color-button-transparent-border-hovered)",
         "transparent-border-active":
            "var(--color-button-transparent-border-active)",
         "transparent-border-disabled":
            "var(--color-button-transparent-border-disabled)",
      },
      badge: {
         text: "var(--color-badge-text)",
      },
      tag: {
         "dark-bg-default": "var(--color-tag-dark-bg-default)",
         "dark-bg-hovered": "var(--color-tag-dark-bg-hovered)",
         "dark-bg-active": "var(--color-tag-dark-bg-active)",
         "dark-bg-disabled": "var(--color-tag-dark-bg-disabled)",
         "dark-text-default": "var(--color-tag-dark-text-default)",
         "dark-text-hovered": "var(--color-tag-dark-text-hovered)",
         "dark-text-active": "var(--color-tag-dark-text-active)",
         "dark-text-disabled": "var(--color-tag-dark-text-disabled)",
         "light-bg-default": "var(--color-tag-light-bg-default)",
         "light-bg-hovered": "var(--color-tag-light-bg-hovered)",
         "light-bg-active": "var(--color-tag-light-bg-active)",
         "light-bg-disabled": "var(--color-tag-light-bg-disabled)",
         "light-text-default": "var(--color-tag-light-text-default)",
         "light-text-hovered": "var(--color-tag-light-text-hovered)",
         "light-text-active": "var(--color-tag-light-text-active)",
         "light-text-disabled": "var(--color-tag-light-text-disabled)",
         "dark-border-default": "var(--color-tag-dark-border-default)",
         "dark-border-hovered": "var(--color-tag-dark-border-hovered)",
         "dark-border-active": "var(--color-tag-dark-border-active)",
         "dark-border-disabled": "var(--color-tag-dark-border-disabled)",
         "light-border-default": "var(--color-tag-light-border-default)",
         "light-border-hovered": "var(--color-tag-light-border-hovered)",
         "light-border-active": "var(--color-tag-light-border-active)",
         "light-border-disabled": "var(--color-tag-light-border-disabled)",
      },
      table: {
         "bg-default": "var(--color-table-bg-default)",
         "bg-contrast": "var(--color-table-bg-contrast)",
         "bg-header": "var(--color-table-bg-header)",
      },
   },
   otherCategories: {
      borderRadius: {
         "radius/inner": "var(--radius-lg)",
      },
   },
   other: {
      gray: {
         100: "#fafafa",
         200: "#eaeaea",
         300: "#e3e3e3",
         400: "#e0e0e0",
         500: "#d9d9d9",
         600: "#cacaca",
         700: "#92939e",
         800: "#727588",
         900: "#25283d",
      },
      brand: {
         100: "#acdeff",
         200: "#73c7ff",
         300: "#39b1ff",
         400: "#009aff",
         500: "#008ae5",
         600: "#065fdb",
         700: "#004eb6",
         800: "#0f00a0",
         900: "#0a0066",
      },
      secondary: {
         100: "#f4faff",
         200: "#e1e6ef",
         300: "#b6c3d8",
         400: "#97abca",
         500: "#7892bc",
         600: "#5575aa",
         700: "#445e88",
         800: "#334666",
         900: "#222f44",
      },
      green: {
         500: "#01cfbf",
         700: "#01a69a",
      },
      orange: {
         500: "#fcbd46",
         700: "#d49215",
      },
      red: {
         500: "#ec5353",
      },
      base: {
         white: "#ffffff",
         black: "#25283d",
         transparent: "#ffffff00",
      },
      primary: {
         100: "#d6f5f3",
         200: "#00e5d5",
         300: "#00cdbe",
         500: "#01beb0",
         700: "#01897f",
         900: "#005650",
      },
      "white-alpha": {
         100: "#ffffffcc",
         300: "#ffffff7a",
         500: "#ffffff52",
         700: "#ffffff1f",
         900: "#ffffff0a",
      },
      icon: {
         inverted: "var(--color-icon-inverted)",
         default: "var(--color-icon-default)",
         "accent-red": "var(--color-icon-accent-red)",
         primary: "var(--color-icon-primary)",
         error: "var(--color-icon-error)",
         warning: "var(--color-icon-warning)",
         less: "var(--color-icon-less)",
         accent: "var(--color-icon-accent)",
         success: "var(--color-icon-success)",
         "accent-brand-less": "var(--color-icon-accent-brand-less)",
      },
      link: {
         default: "var(--color-link-default)",
         disabled: "var(--color-link-disabled)",
         active: "var(--color-link-active)",
         visited: "var(--color-link-visited)",
         hover: "var(--color-link-hover)",
         "inverted-default": "var(--color-link-inverted-default)",
         "inverted-disabled": "var(--color-link-inverted-disabled)",
         "inverted-hovered": "var(--color-link-inverted-hovered)",
      },
      fill: {
         default: "var(--color-fill-default)",
         more: "var(--color-fill-more)",
         most: "var(--color-fill-most)",
         brand: "var(--color-fill-brand)",
         accent: "var(--color-fill-accent)",
         error: "var(--color-fill-error)",
         "accent-less": "var(--color-fill-accent-less)",
      },
      price: {
         default: "var(--color-price-default)",
         before: "var(--color-price-before)",
         discounted: "var(--color-price-discounted)",
      },
      availability: {
         "in-stock": "var(--color-availability-in-stock)",
         "out-of-stock": "var(--color-availability-out-of-stock)",
      },
      opening: {
         "status-open": "var(--color-opening-status-open)",
         "status-closed": "var(--color-opening-status-closed)",
         "status-open-today": "var(--color-opening-status-open-today)",
      },
   },
};
